with import <nixpkgs/lib>;
with builtins;

let
  # Colors generated by going to https://colordesigner.io/gradient-generator and picking.
  background = "#1c1c1c";
  foreground = "#ffffff";
  dimForeground = "#aaa";
  highlight = "#004799";
  fadeColors =
    [ background "#004799" "#1e3b8c" "#2b2f7f" "#322270" "#361362" "#380053" ];
  gradientOpts = {
    name = "r";
    colors = fadeColors;
    separator = " %{T4}%{T-}";
  };

  gradient = (import ./polybar-gradient.nix) gradientOpts [
    null
    (bg: {
      type = "internal/cpu";
      interval = 2;
      format-prefix = "%{T3}%{T-} ";
      format-background = bg;
      format-prefix-foreground = dimForeground;
      label = "%percentage:2%%";
    })
    null
    (bg: {
      type = "internal/memory";
      interval = 2;
      format-prefix = "%{T3}%{T-} ";
      format-background = bg;
      format-prefix-foreground = dimForeground;
      label = "%percentage_used%%";
    })
    null
    (bg: {
      type = "custom/script";
      exec = "~/bin/polybar-battery.sh";
      interval = 5;
      format-background = bg;
    })
    null
    (bg: {
      type = "internal/network";
      interface = "wlp3s0";
      interval = "3.0";

      label-connected =
        "%{T3}%{F${dimForeground}}%{F-}%{T-} %upspeed% %{T3}%{F${dimForeground}}%{F-}%{T-} %downspeed%";
      label-connected-background = bg;

      label-disconnected = "%{T3}睊%{T-}";
      label-disconnected-background = bg;
    })
    null
    (bg: {
      type = "internal/date";
      interval = 3;

      date = "%m/%d";
      time = "%H:%M";
      label = "%date% %time%";

      format-prefix = "%{T3}%{T-} ";
      format-prefix-foreground = dimForeground;

      format-background = bg;
    })
    null
    (bg: {
      type = "custom/text";
      content = "%{T2}卑%{T-} %{T2}%{T-} %{T2}理%{T-} ";
      content-background = bg;
    })
  ];

  i3Icons = icons:
    listToAttrs (imap0 (i: icon: {
      name = "ws-icon-${toString i}";
      value = "${toString (i + 1)};${icon}";
    }) icons);

in {
  "bar/bar" = {
    width = "100%";
    height = "34";
    fixed-center = true;

    background = background;
    foreground = foreground;

    modules-left = "i3";
    modules-center = "cmus";

    modules-right = gradient.names;

    # General text font.
    font-0 = "iosevka:pixelsize=12;2";
    # Workspace icons.
    font-1 = "iosevka:pixelsize=24;4";
    # Right-side bar icons.
    font-2 = "iosevka:pixelsize=20;4";
    # Separator.
    font-3 = "iosevka:pixelsize=30;6";
    # Fallback for Japanese and such.
    font-4 = "unifont:pixelsize=14;2";
  };

  "module/cmus" = rec {
    type = "custom/script";
    exec = toString ./polybar-cmus.sh;
    exec-if = "pgrep -x cmus";
    interval = 1;

    format = "<label>";
    format-prefix = " ";
    format-prefix-font = 3;
    format-prefix-foreground = "#00a2d3";
    format-suffix = " ";
    format-suffix-font = format-prefix-font;
    format-suffix-foreground = format-prefix-foreground;
    label = "%{T3} %{T-}%output%";
    label-maxlen = 75;
  };

  "module/i3" = {
    type = "internal/i3";
    format = "<label-state> <label-mode>";
    index-sort = true;

    label-mode-padding = 2;

    label-focused = "%icon%";
    label-focused-foreground = "#ffffff";
    label-focused-background = highlight;
    label-focused-padding = 1;
    label-focused-font = 2;

    label-unfocused = "%icon%";
    label-unfocused-foreground = "#60ffffff";
    label-unfocused-padding = 1;
    label-unfocused-font = 2;

    label-urgent = "%icon%";
    label-urgent-foreground = "#ffffff";
    label-urgent-padding = 1;
    label-urgent-font = 2;
  } // (i3Icons [
    ""
    ""
    ""
    ""
    ""
    ""
    "%{T1}7%{T-}"
    "%{T1}8%{T-}"
    "%{T1}9%{T-}"
  ]);
} // gradient.modules
